import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/NavBar'
import WatchList from '../components/WatchList'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.header}>
          <NavBar />
        </section>
        <section className={styles.main}>
      <div className={styles.watch}>
     <WatchList />
      </div>
        </section>
      </main>
    </div>
  )
}
